#!/bin/sh

TESTSUITE_DIR=/$($(dirname $0)/../rules echo-MOZ_TESTDIR 2>/dev/null)

export LC_ALL=en_US.UTF-8

$TESTSUITE_DIR/run_reftest --own-display --own-session-bus $TESTSUITE_DIR/reftest/tests/testing/crashtest/crashtests.list
